In [56]:
#1. Import the numpy package under the name np 
import numpy as np

In [57]:
# 2. Print the numpy version and the configuration 
np.__version__, np.show_config



('1.16.5', <function numpy.__config__.show()>)

In [3]:
#3. Create a null vector of size 10
np.zeros(10)

array([0., 0., 0., 0., 0., 0., 0., 0., 0., 0.])

In [62]:
#4. How to find the memory size of any array 
 # By Using <size> and <itemsize> attributes of NumPy array. 

V=np.array([[1,2,3],[1,2,3]])
print("%d bytes" % (V.size * V.itemsize))

24 bytes


In [60]:
# 5. How to get the documentation of the numpy add function from the command line? 
#np.info(np.add)
%run `python -c "import numpy; numpy.info(numpy.add)"

In [63]:
# 6. Create a null vector of size 10 but the fifth value which is 1 
D=np.zeros(10)
D[4] = 1
print(D)

[0. 0. 0. 0. 1. 0. 0. 0. 0. 0.]


In [23]:
7. # Create a vector with values ranging from 10 to 49
np.arange(10,50)

array([10, 11, 12, 13, 14, 15, 16, 17, 18, 19, 20, 21, 22, 23, 24, 25, 26,
       27, 28, 29, 30, 31, 32, 33, 34, 35, 36, 37, 38, 39, 40, 41, 42, 43,
       44, 45, 46, 47, 48, 49])

In [64]:
#8. Reverse a vector (first element becomes last)

y = np.arange(10, 35)
print("Original array:")
print(y)
print("Reverse array:")
y = y[::-1]
print(y)

Original array:
[10 11 12 13 14 15 16 17 18 19 20 21 22 23 24 25 26 27 28 29 30 31 32 33
 34]
Reverse array:
[34 33 32 31 30 29 28 27 26 25 24 23 22 21 20 19 18 17 16 15 14 13 12 11
 10]


In [28]:
#9. Create a 3x3 matrix with values ranging from 0 to 8
x =  np.arange(0, 9).reshape(3,3)
print(x)


[[0 1 2]
 [3 4 5]
 [6 7 8]]


In [30]:
#11. Create a 3x3 identity matrix
d=np.eye(3)
print(d)

[[1. 0. 0.]
 [0. 1. 0.]
 [0. 0. 1.]]


In [38]:
#12. Create a 3x3x3 array with random values 

Z = np.random.random((3,3,3))
print(Z)

[[[0.01667501 0.49919976 0.01510151]
  [0.85962532 0.95733957 0.80488778]
  [0.03907855 0.94861227 0.52369993]]

 [[0.90220265 0.70230869 0.46684425]
  [0.25884098 0.46794496 0.99631157]
  [0.26367376 0.74695336 0.31937656]]

 [[0.65448071 0.45885834 0.42051923]
  [0.34280668 0.47899425 0.87795294]
  [0.08501293 0.71467799 0.9115744 ]]]


In [39]:
#13. Create a 10x10 array with random values and find the minimum and maximum values 
Z = np.random.random((10,10))
Zmin, Zmax = Z.min(), Z.max()
print(Zmin, Zmax)

0.0033260726092718684 0.9844010932819076


In [40]:
#14. Create a random vector of size 30 and find the mean value
Z = np.random.random(30)
m = Z.mean()
print(m)

0.4443786994331726


In [41]:
#15. Create a 2d array with 1 on the border and 0 inside

Z = np.ones((10,10))
Z[1:-1,1:-1] = 0
print(Z)

[[1. 1. 1. 1. 1. 1. 1. 1. 1. 1.]
 [1. 0. 0. 0. 0. 0. 0. 0. 0. 1.]
 [1. 0. 0. 0. 0. 0. 0. 0. 0. 1.]
 [1. 0. 0. 0. 0. 0. 0. 0. 0. 1.]
 [1. 0. 0. 0. 0. 0. 0. 0. 0. 1.]
 [1. 0. 0. 0. 0. 0. 0. 0. 0. 1.]
 [1. 0. 0. 0. 0. 0. 0. 0. 0. 1.]
 [1. 0. 0. 0. 0. 0. 0. 0. 0. 1.]
 [1. 0. 0. 0. 0. 0. 0. 0. 0. 1.]
 [1. 1. 1. 1. 1. 1. 1. 1. 1. 1.]]


In [43]:

#17. What is the result of the following expression? 
0 * np.nan
np.nan == np.nan
np.inf > np.nan
np.nan - np.nan
np.nan in set([np.nan])
0.3 == 3 * 0.1


print(0 * np.nan)
print(np.nan == np.nan)
print(np.inf > np.nan)
print(np.nan - np.nan)
print(np.nan in set([np.nan]))
print(0.3 == 3 * 0.1)

nan
False
False
nan
True
False


In [44]:
#18. Create a 5x5 matrix with values 1,2,3,4 just below the diagonal 

Z = np.diag(1+np.arange(4),k=-1)
print(Z)

[[0 0 0 0 0]
 [1 0 0 0 0]
 [0 2 0 0 0]
 [0 0 3 0 0]
 [0 0 0 4 0]]


In [45]:
#19. Create a 8x8 matrix and fill it with a checkerboard pattern 
Z = np.zeros((8,8),dtype=int)
Z[1::2,::2] = 1
Z[::2,1::2] = 1
print(Z)

[[0 1 0 1 0 1 0 1]
 [1 0 1 0 1 0 1 0]
 [0 1 0 1 0 1 0 1]
 [1 0 1 0 1 0 1 0]
 [0 1 0 1 0 1 0 1]
 [1 0 1 0 1 0 1 0]
 [0 1 0 1 0 1 0 1]
 [1 0 1 0 1 0 1 0]]


In [46]:
#20. Consider a (6,7,8) shape array, what is the index (x,y,z) of the 100th element?

print(np.unravel_index(99,(6,7,8)))


(1, 5, 3)


In [47]:
# 21. 21. Create a checkerboard 8x8 matrix using the tile function

Z = np.tile( np.array([[0,1],[1,0]]), (4,4))
print(Z)

[[0 1 0 1 0 1 0 1]
 [1 0 1 0 1 0 1 0]
 [0 1 0 1 0 1 0 1]
 [1 0 1 0 1 0 1 0]
 [0 1 0 1 0 1 0 1]
 [1 0 1 0 1 0 1 0]
 [0 1 0 1 0 1 0 1]
 [1 0 1 0 1 0 1 0]]


In [48]:
# 22. Normalize a 5x5 random matrix

Z = np.random.random((5,5))
Z = (Z - np.mean (Z)) / (np.std (Z))
print(Z)

[[ 0.21945159 -1.06596477 -0.51261365  0.90345621 -1.85686215]
 [ 1.69984572  1.58371295  0.90115769 -0.18742586 -0.12961146]
 [-0.98725467 -0.27088177  1.01174016  0.49987521  1.73522613]
 [-0.14167212 -0.92728559 -1.24547596  0.05221174  0.07110573]
 [-1.30031595  0.95788496 -0.85390933  0.89795639 -1.05435117]]
