#Vectors and Matrices

In [ ]:
#VECTORS

In [6]:
#Write a function add_vectors(u, v) that takes two lists of numbers of the same length, and returns a new list containing the sums of the corresponding elements of each.
import numpy as np


def add_vectors(u,v):
    return np.add(u,v)
    #c=np.add(u,v)
    #print(c)
    
u= [1,2,3]   
v = [1.5,2,3]

 
#add_vectors(u,v)
#add_vectors([1, 2, 1], [1, 4, 3])
add_vectors([11, 0, -4, 5], [2, -4, 17, 0])

array([13, -4, 13,  5])

In [13]:
#Write a function scalar_mult(s, v) that takes a number, s, and a list, v and returns the scalar multiple of v by s.

#without numpy
def scalar_mult(s, v):
    m=[]
    for x in v:
        m.append(s*x)
    return m
    

#scalar_mult(5, [1, 2])  
#scalar_mult(3, [1, 0, -1])
scalar_mult(7, [3, 0, 5, 11, 2])


[21, 0, 35, 77, 14]

In [14]:
#with np
def scalar_mult_np(s, v):
    return s*np.array(v)
scalar_mult_np(5, [1, 2])

array([ 5, 10])

In [17]:
#Write a function dot_product(u, v) that takes two lists of numbers of the same length, and returns the sum of the products of the corresponding elements of each (the dot_product.

# without numpy
def dot_product(u, v):
    c = [u*v for u,v in zip(u,v)]
    return sum(c)
   
#dot_product([1, 1], [1, 1])
dot_product([1, 2], [1, 4])
#dot_product([1, 2, 1], [1, 4, 3])
#dot_product([2, 0, -1, 1], [1, 5, 2, 0])

9

In [19]:

#with np
def dot_product_np(a,b):
    return np.dot(a,b)
dot_product_np([1, 2], [1, 4])

9

In [27]:
#Matrices

In [28]:

#Create a new module named matrices.py or use the Jupyter notebook provided and add the following function, which returns a copy of nested lists of numbers such that the lists are not aliases:

def copy_matrix(matrix):
    return matrix.copy()
    
#copy_matrix([[1, 2], [3, 4]])
copy_matrix([[1, 2], [3, 4], [5, 6], [7, 8]])


[[1, 2], [3, 4], [5, 6], [7, 8]]

In [32]:

#using vstack
def add_row(matrix):
    m=[]
    for x in matrix:
        a=len(x)
    for i in range(a):
        m.append(0)
    return np.vstack([matrix,m])
    
    """
      >>> m = [[0, 0], [0, 0]]
      >>> add_row(m)
      [[0, 0], [0, 0], [0, 0]]
      >>> n = [[3, 2, 5], [1, 4, 7]]
      >>> add_row(n)
      [[3, 2, 5], [1, 4, 7], [0, 0, 0]]
      >>> n
      [[3, 2, 5], [1, 4, 7]]
    """
    
n = [[3, 2, 5], [1, 4, 7]]
add_row(n) 
#m = [[0, 0], [0, 0]]
#add_row(m)
# [[0, 0], [0, 0], [0, 0]]

array([[3, 2, 5],
       [1, 4, 7],
       [0, 0, 0]])

In [36]:
#Write a function add_matrices(m1, m2) that adds m1 and m2 and returns a new matrix containing their sum. You can assume that m1 and m2 are the same size. You add two matrices by adding their corresponding values.

def add_matrices_np(a, b):
    a=np.matrix(a)
    b=np.matrix(b)
    #we could double check it is a matrix and so on
    return a+b



a = [[1, 2], [3, 4]]
b = [[2, 2], [2, 2]]
add_matrices_np(a, b)

matrix([[3, 4],
        [5, 6]])

In [38]:
#Write a function scalar_mult(s, m) that multiplies a matrix, m, by a scalar, s.

# numpy
def scalar_mult(s, m):
    m=np.matrix(m)
    return s*m

    
a = [[1, 2], [3, 4]]
scalar_mult(3, a)

matrix([[ 3,  6],
        [ 9, 12]])

In [42]:
#write functions row_times_column and matrix_mult:

def row_times_column(m1, row, m2, column):
    a=np.matmul(m1, m2)
    return  a[row][column]

   
#row_times_column([[1, 2], [3, 4]], 0, [[5, 6], [7, 8]], 0)
#row_times_column([[1, 2], [3, 4]], 1, [[5, 6], [7, 8]], 0)
row_times_column([[1, 2], [3, 4]], 1, [[5, 6], [7, 8]], 1)    

50

In [49]:
#Write a function transpose that takes a matrix as an argument and returns is transpose:


def transpose_np(m):
    m = np.array(m)
    return m.T

#m = [[3, 4, 6]]
#transpose_np(m)
m = [[3, 1], [4, 5], [6, 9]]
transpose_np(m)
    

array([[3, 4, 6],
       [1, 5, 9]])